version: 2.1
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/blog
    environment:
      HUGO_BUILD_DIR: ~/blog/public
    steps:
      - run: sudo apt-get update && sudo apt-get install git
      - checkout
      - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR
      - add_ssh_keys:
          fingerprints:
            - "6e:87:ad:fe:9e:fc:9c:24:b7:cd:20:80:9b:c1:81:cb"
      - deploy:
          name: deploy to VPS
          command: |
            if [ "${CIRCLE_BRANCH}" = "main" ]; then
              rsync -azv -e "ssh -o StrictHostKeyChecking=no -p ${DEPLOY_PORT}" --delete ${HUGO_BUILD_DIR}/ ${DEPLOY_USER}@${DEPLOY_HOST}:~/blog
            else
              echo "Not main branch, dry run only"
            fi
