version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/blog
    environment:
      HUGO_BUILD_DIR: ~/blog/public
    steps:
      - run: apk update && apk add git
      - checkout
      - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR
      - add_ssh_keys:
          fingerprints:
            - "7b:8f:bf:5b:1e:6d:53:78:d2:14:ca:57:90:0d:cd:ee"
      - deploy:
          name: deploy to VPS
          command: |
            if [ "${CIRCLE_BRANCH}" = "main" ]; then
              rsync -azv -e "ssh -o StrictHostKeyChecking=no -p ${DEPLOY_PORT}" --delete ${HUGO_BUILD_DIR}/ ${DEPLOY_USER}@${DEPLOY_HOST}:~/blog
            else
              echo "Not main branch, dry run only"
            fi
